m-lair/MovieClub

- MovieClub.xcodeproj/project.pbxproj
- MovieClub.xcodeproj/project.xcworkspace/xcuserdata/marcus.xcuserdatad/Bookmarks/bookmarks.plist
- MovieClub.xcodeproj/xcuserdata/marcus.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
- MovieClub/Model/Model.swift
- MovieClub/MovieClub.entitlements
- MovieClub/ViewModel/DataManager.swift
- MovieClub/Views/Clubs/ClubDetailsForm.swift
- MovieClub/Views/Clubs/ComingSoonView.swift
- MovieClub/Views/User/LoginView.swift
- MovieClub/Views/User/ProfileHeaderView.swift
- MovieClub/Views/User/ProfileView.swift
- MovieClub/Views/User/SignUpView.swift
- MovieClub/Views/User/UserEditView.swift
> Working Build 

- MovieClub.xcodeproj/project.pbxproj
- MovieClub.xcodeproj/project.xcworkspace/xcuserdata/marcus.xcuserdatad/Bookmarks/bookmarks.plist
- MovieClub.xcodeproj/xcuserdata/marcus.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
- MovieClub/ViewModel/DataManager.swift
- MovieClub/Views/Clubs/ClubDetailView.swift
- MovieClub/Views/Clubs/ComingSoonRowView.swift
- MovieClub/Views/Clubs/ComingSoonView.swift
- MovieClub/Views/Clubs/CommentDetailView.swift
- MovieClub/Views/Clubs/CommentInputView.swift
- MovieClub/Views/Clubs/CommentView.swift
- MovieClub/Views/Clubs/FeaturedMovieView.swift
- MovieClub/Views/User/AviSelector.swift
- MovieClub/Views/User/CircularImageView.swift
- MovieClub/Views/User/UserMembershipsView.swift
fixed some club creations issues
fix comment order
change avi url methods
> changed row view style for now

- functions/README.md
- functions/src/movieClubs/movieClubFunctions.ts
- functions/src/movieClubs/movies/comments/commentFunctions.ts
- functions/src/users/userFunctions.ts
- functions/src/users/userTypes.ts
- functions/test/mocks/comment.ts
- functions/test/mocks/membership.ts
- functions/test/mocks/user.ts
- functions/test/src/movieClubs/movieClubFunctions.test.ts
- functions/test/src/movieClubs/movies/comments/commentFunctions.test.ts
- functions/test/src/users/userFunctions.test.ts
> Functions: Use auth parameters

- functions/eslint.config.mjs
- functions/package.json
- functions/test/clearDb.ts
- functions/test/index.test.ts
- functions/test/testHelper.ts
run with `npm run reset` inside the functions folder
> Reset script

- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- MovieClub/Views/ComponentViews/MovieButtonViews.swift
> Updates to format buttons and handle some refactoring

- MovieClub.xcodeproj/project.pbxproj
- MovieClub/Controllers/DataManager.swift
- MovieClub/Controllers/SuggestionManager.swift
- MovieClub/Controllers/UserManager.swift
- MovieClub/Models/Club.swift
- MovieClub/Models/CollectionItem.swift
- MovieClub/Models/Movie.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
- functions/index.ts
- functions/src/index.ts
- functions/src/users/posters/posterFunctions.ts
- functions/src/users/posters/posterHelpers.ts
- functions/src/users/posters/posterTypes.ts
- functions/src/utilities/collectionNames.ts
Collection of posters works and stores poster under the user document in "posters". docId = movieId
closes #58
> 58 function user collection

- MovieClub.xcodeproj/project.pbxproj
local build working. trying to fix cloud build
> add input and output file

- MovieClub.xcodeproj/project.pbxproj
- MovieClub/ContentView.swift
- MovieClub/Controllers/ClubManager.swift
- MovieClub/Controllers/CommentManager.swift
- MovieClub/Controllers/UserManager.swift
- MovieClub/Models/Club.swift
- MovieClub/Models/Comment.swift
- MovieClub/Models/Movie.swift
- MovieClub/Models/User.swift
- MovieClub/Views/Clubs/ClubDetailView.swift
- MovieClub/Views/Clubs/ClubEditView.swift
- MovieClub/Views/Clubs/Create/ClubDetailsForm.swift
- MovieClub/Views/Clubs/Create/NewClubView.swift
- MovieClub/Views/Clubs/MovieClubCardView.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- MovieClub/Views/ComponentViews/ClubToolbar.swift
- MovieClub/Views/EmptyViews/WaveLoadingView.swift
- MovieClub/Views/Movie/MovieRowView.swift
- MovieClub/Views/Movie/StarRatingView.swift
- MovieClub/Views/Tabs/HomePageView.swift
- MovieClub/Views/Tabs/MainTabView.swift
- functions/src/movieClubs/movieClubFunctions.ts
- functions/src/movieClubs/movieClubTypes.ts
- functions/test/src/movieClubs/movieClubFunctions.test.ts
> Revert "Develop"

- MovieClub/Controllers/DataManager.swift
- MovieClub/MovieClubApp.swift
- MovieClub/Util/AppleAuth.swift
- MovieClub/Util/AuthManager.swift
- MovieClub/Views/Clubs/CommentViews/CommentDetailView.swift
- MovieClub/Views/Clubs/Create/ClubDetailsForm.swift
- MovieClub/Views/ContentView.swift
- MovieClub/Views/Tabs/ProfileView.swift
- MovieClub/Views/User/LoginView.swift
- MovieClub/Views/User/Profile/ProfileDisplayView.swift
- MovieClub/Views/User/Settings/SettingsView.swift
- MovieClub/Views/User/SignUpView.swift
> refactor auth and fix previous release

- functions/package-lock.json
- functions/src/movieClubs/movieClubFunctions.ts
- functions/src/movieClubs/movies/comments/commentFunctions.ts
- functions/src/movieClubs/movies/comments/commentHelpers.ts
- functions/src/movieClubs/movies/comments/commentTypes.ts
- functions/src/movieClubs/movies/movieFunctions.ts
- functions/src/movieClubs/movies/movieTypes.ts
- functions/src/movieClubs/suggestions/suggestionFunctions.ts
- functions/src/users/memberships/membershipFunctions.ts
- functions/src/utilities/helpers.ts
- functions/test/mocks/comment.ts
- functions/test/src/movieClubs/movieClubFunctions.test.ts
- functions/test/src/movieClubs/movies/comments/commentFunctions.test.ts
- functions/test/src/movieClubs/suggestions/suggestionFunctions.test.ts
- functions/test/src/users/memberships/memberships.test.ts
Some quick formatting, refactors and test fixes.
Added tests for liking and unliking comments.
> Functions Cleanup and Test Fixes

- MovieClub/Views/Clubs/Create/NewClubView.swift
> add isPublic check

- MovieClub/Controllers/UserManager.swift
- MovieClub/Views/Clubs/ComingSoon/ComingSoonView.swift
fix watch period calcualtion
closes #97
> 97 feedback my current watch period

- MovieClub/Controllers/DataManager.swift
- MovieClub/Controllers/MembershipManager.swift
- MovieClub/Controllers/UserManager.swift
- MovieClub/MovieClubApp.swift
- MovieClub/Util/AuthManager.swift
- MovieClub/Views/Clubs/ClubToolbar.swift
- MovieClub/Views/Clubs/Create/ClubDetailsForm.swift
- MovieClub/Views/Clubs/Create/NewClubView.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- MovieClub/Views/ContentView.swift
- MovieClub/Views/Tabs/HomePageView.swift
- MovieClub/Views/User/LoginView.swift
this adjusts some load order relating to when a user add and removes clubs fixing animations related to those.
also allows users to click report problem and a new safari tab is opened to the public git repo
and now only the owner can edit the club page
closes #129
> 129 any user can see the edit club page

- MovieClub/Controllers/UserManager.swift
- MovieClub/Util/AuthManager.swift
- MovieClub/Views/Clubs/CommentViews/CommentInputView.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- comment view scrolls to bottom when comment is posted
- comment post doesnt lock up anymore
closes #132
> comment view scrolls to bottom when comment is posted

- MovieClub/Controllers/UserManager.swift
- MovieClub/Views/User/Profile/UserEditView.swift
- MovieClub/Views/User/Settings/SettingsView.swift
update design of user settings view
update update functionality for users
chore: allow users to update email and password in cloud functions
closes #134
> 134 fix update user functionality

- MovieClub/Controllers/UserManager.swift
- MovieClub/Models/Movie.swift
- MovieClub/MovieClubApp.swift
- MovieClub/Views/Clubs/NowShowing/MovieButtonViews.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- SwiftTesting/AppTests.swift
- functions/src/movieClubs/movies/movieFunctions.ts
- functions/src/movieClubs/movies/movieTypes.ts
- functions/src/movieClubs/suggestions/suggestionFunctions.ts
- package-lock.json
movie like and dislikes for 0.1
needs an extra set of eyes on functions side @Codball 
closes #136
> like and dislike movies

- MovieClub.xcodeproj/xcshareddata/xcschemes/MovieClub.xcscheme
- MovieClub/Config/Firebase.swift
- MovieClub/Controllers/UserManager.swift
- MovieClub/Models/CollectionItem.swift
- MovieClub/Models/Movie.swift
- MovieClub/Views/Clubs/Create/ClubDetailsForm.swift
- MovieClub/Views/Tabs/HomePageView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
- functions/package-lock.json
- functions/src/users/posters/posterFunctions.ts
- functions/src/users/posters/posterTypes.ts
> 93 feedback the profile collection page only does green border

- MovieClub/Controllers/UserManager.swift
- MovieClub/Views/Clubs/NowShowing/MovieButtonViews.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- functions/src/movieClubs/movies/movieFunctions.ts
- functions/src/movieClubs/movies/movieTypes.ts
fixes some bugs and poor state managment
> Movie like dislike refactor

- MovieClub/Controllers/UserManager.swift
- MovieClub/Models/CollectionItem.swift
- MovieClub/Models/User.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- SwiftTesting/AppTests.swift
- SwiftTesting/MockServices/MockFirebaseServices.swift
- SwiftTesting/Posters/PostersTests.swift
- SwiftTesting/Users/Users.test.swift
- functions/src/users/posters/posterFunctions.ts
- functions/src/users/posters/posterTypes.ts
submitting current refactors for the tests. this will require larger changes so im breaking them out into multiple PRs
> Refactor tests copy

- MovieClub/Features/Clubs/ClubManager.swift
- MovieClub/Features/Posters/CollectionItem.swift
- MovieClub/Features/Posters/PosterManager.swift
- MovieClub/Features/Suggestions/SuggestionManager.swift
- MovieClub/Util/APIController.swift
- MovieClub/Views/Clubs/ComingSoon/ComingSoonView.swift
- MovieClub/Views/Clubs/ComingSoon/Suggestions/CreateSuggestion.swift
- MovieClub/Views/Clubs/NowShowing/FeaturedMovieView.swift
fatal error in fetching collection with new api is fixed plus other minor fixes and formatting
> Tmdb bug fix

- MovieClub.xcodeproj/project.pbxproj
- SwiftTesting/Clubs/ClubTests.swift
- SwiftTesting/MockServices/FunctionsService.swift
- SwiftTesting/MockServices/MockFirebaseServices.swift
- SwiftTesting/Posters/PostersTests.swift
- functions/src/movieClubs/movieClubFunctions.ts
- functions/src/users/posters/posterFunctions.ts
- functions/src/users/posters/posterTypes.ts
- functions/test/src/movieClubs/movieClubFunctions.test.ts
club and posters are also returning their documentId which was referenced in #156
> Simple Club tests and fixed poster attrb name issue

- MovieClub/Util/APIController.swift
> update endpoint usage

- functions/index.ts
- functions/src/index.ts
- functions/src/movieClubs/movies/movieHelpers.ts
- functions/src/notifications/commentNotifications.ts
- functions/src/notifications/posterNotifications.ts
add more notifications 
- collect poster
- comments (likes & replies)
> Notifications swift

- MovieClub.xcodeproj/project.pbxproj
- MovieClub/Views/Clubs/Archive/ArchiveRowView.swift
- MovieClub/Views/Clubs/Archive/ArchivesView.swift
- MovieClub/Views/Clubs/Archive/CommentsSheetView.swift
- MovieClub/Views/Clubs/NowShowing/FeaturedMovieView.swift
> Archives work with comments retrieval

- MovieClub/Views/ComponentViews/DiamondCardView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
added new poster and a placeholder discover view
> add placeholder discover view

- MovieClub/Features/Clubs/ClubManager.swift
- MovieClub/Features/Posters/PosterManager.swift
- MovieClub/Features/Users/UserManager.swift
- MovieClub/MainTabView.swift
- MovieClub/Util/Notifications/Notification.swift
- MovieClub/Util/Notifications/NotificationManager.swift
- MovieClub/Views/Clubs/CommentViews/CommentDetailView.swift
- MovieClub/Views/Clubs/Create/NewClubView.swift
- MovieClub/Views/Tabs/DiscoverView.swift
- MovieClub/Views/Tabs/HomePageView.swift
- MovieClub/Views/Tabs/NotifListView.swift
- MovieClub/Views/Tabs/ProfileView.swift
- MovieClub/Views/User/Profile/ProfileDisplayView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
- MovieClub/Views/User/Profile/UserMembershipsView.swift
- functions/src/notifications/commentNotifications.ts
- functions/src/notifications/notificationTypes.ts
- functions/src/notifications/posterNotifications.ts
- functions/src/users/userTypes.ts
notifications and discover page links will update
> add navigation

- MovieClub/Features/Clubs/Club.swift
- MovieClub/Features/Clubs/ClubManager.swift
- MovieClub/Features/Comments/Comment.swift
- MovieClub/Util/DataManager.swift
- MovieClub/Views/Clubs/Archive/CommentsSheetView.swift
- MovieClub/Views/Clubs/CommentViews/CommentDetailView.swift
- MovieClub/Views/Clubs/CommentViews/CommentsView.swift
- MovieClub/Views/Clubs/Create/NewClubView.swift
- MovieClub/Views/Tabs/DiscoverView.swift
- MovieClub/Views/Tabs/HomePageView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
- functions/src/notifications/commentNotifications.ts
new club view rows
discover view reserves space now
> minor visual updates

- MovieClub/Util/Notifications/Notification.swift
- MovieClub/Util/Notifications/NotificationManager.swift
- MovieClub/Views/Notifications/NotifView.swift
- MovieClub/Views/Tabs/NotifListView.swift
- functions/index.ts
- functions/src/index.ts
- functions/src/movieClubs/movies/movieFunctions.ts
- functions/src/notifications/commentNotifications.ts
- functions/src/notifications/movieClubNotifications.ts
- functions/src/notifications/notificationFunctions.ts
- functions/src/notifications/posterNotifications.ts
- functions/src/notifications/suggestionNotifications.ts
delete functionality for notifications
more notifications added
notification filters and redesigned UI
> Delete notifs func and new notifs

- MovieClub.xcodeproj/project.pbxproj
- MovieClub/Features/Comments/CommentManager.swift
- MovieClub/Views/Clubs/CommentViews/CommentDetailView.swift
- MovieClub/Views/Clubs/CommentViews/CommentInputView.swift
- MovieClub/Views/Clubs/CommentViews/CommentMenuView.swift
- MovieClub/Views/Clubs/CommentViews/CommentsView.swift
- SwiftTesting/Comments/CommentTests.swift
- SwiftTesting/MockServices/FunctionsService.swift
- SwiftTesting/MockServices/MockFirebaseServices.swift
- functions/src/movieClubs/movies/comments/commentFunctions.ts
- functions/src/movieClubs/movies/comments/commentTypes.ts
- functions/test/src/movieClubs/movies/comments/commentFunctions.test.ts
add delete comment feature (removes user data)
remove old delete comment feature
report comment feature
> edit comment input function

- MovieClub/Features/Clubs/ClubManager.swift
- MovieClub/Views/Clubs/ClubEditView.swift
- MovieClub/Views/Clubs/CommentViews/CommentInputView.swift
- MovieClub/Views/ComponentViews/DiamondCardView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
- functions/src/movieClubs/movieClubFunctions.ts
This pull request includes several improvements and bug fixes to the `MovieClub` project, focusing on better error handling, user feedback, and performance optimization. The most important changes include enhancing the `updateMovieClub` function, adding a delay before hiding the checkmark in `CommentInputView`, switching to `CachedAsyncImage` for better image loading, and updating the Firebase function to return a structured response.
* [`MovieClub/Features/Clubs/ClubManager.swift`](diffhunk://#diff-9f7ab8ebb1821aab61406bfd430579d41fedbdea41795d8427d5e6db5dfa5d97R69-R81): Improved error handling and added print statements for better feedback when updating a movie club.
* [`functions/src/movieClubs/movieClubFunctions.ts`](diffhunk://#diff-9bea8c328d131d2dc4cb5d2a4c041f6f3cceb8cf13b07f263778 …
> Club edit UI update

- MovieClub.xcodeproj/project.pbxproj
- MovieClub/Features/Clubs/ClubManager.swift
- MovieClub/Features/Movies/MovieManager.swift
- MovieClub/Features/Posters/CollectionItem.swift
- MovieClub/Features/Posters/PosterManager.swift
- MovieClub/Info.plist
- MovieClub/MovieClubApp.swift
- MovieClub/Util/APIController.swift
- MovieClub/Util/FontExtensions.swift
- MovieClub/Util/VersionManager.swift
- MovieClub/Views/Clubs/NowShowing/NowShowingView.swift
- MovieClub/Views/ComponentViews/DiamondCardView.swift
- MovieClub/Views/ComponentViews/WhatsNewView.swift
- MovieClub/Views/Tabs/HomePageView.swift
- MovieClub/Views/User/Profile/UserCollection.swift
also whats new view and made sure fonts were working better
> Collection view timers
